name: Running gtests on pull request to main
on:
  # Triggers the workflow pull request events but only for the master (main) branch.
  pull_request:
    branches: [ master, main, feature_branch_1 ]
  
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

env:
  LINE_COV_GATE: 50
  MCDC_COV_GATE: 50
  DTP_PROJECT: ATM_testing

permissions:
  contents: read
  pages: write
  id-token: write
  security-events: write
  # only required for workflows in private repositories
  actions: read

jobs:
  build:
    runs-on: self-hosted
    continue-on-error: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set build id
      shell: bash
      working-directory: ${{github.workspace}}
      run: echo "build_id=build-$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV 

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -DCPPTEST_COVERAGE=ON CPPTEST_HOME=/opt/Parasoft/cpptest-ct -S . -B build

    - name: Build Project
      working-directory: ${{github.workspace}}
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build build

    - name: Run Unit Tests
      
      shell: bash
      run: |
        rm -rf build/cpptest-coverage/ATMproject_lib/ATMproject_lib.clog
        rm -rf build/gtest_results.xml
        ./atm_gtest --gtest_output=xml:build/atm_gtest_results.xml
      continue-on-error: true

    - name: Compute Coverage
      working-directory: ${{github.workspace}}/build
      run: |
        cpptestcov compute -map cpptest-coverage/ATMproject_lib/.cpptest -clog cpptest-coverage/ATMproject_lib/ATMproject_lib.clog -out .coverage

    - name: Report Coverage to Console
      working-directory: ${{github.workspace}}/build
      run: |
        cpptestcov report text .coverage

    - name: Compute Index for VS Code
      working-directory: ${{github.workspace}}/build
      run: |
        cpptestcov index .coverage

    - name: Generate Coverage Reports
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run:  cpptestcov report html .coverage -code -out .coverage/coverage.html

    - name: Publish Reports to DTP
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run:  cpptestcov report dtp -property build.id=${build_id} -property dtp.project=${DTP_PROJECT} .coverage atm_gtest_results.xml

    - name: Setup Pages
      uses: actions/configure-pages@v5
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload coverage reports
        path: ${{github.workspace}}/build/.coverage
      
    - name: Archive reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: CpptestCTReports
        include-hidden-files: true
        path: |
          build/.coverage/*.*

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Show Coverage HTML Link
      shell: bash
      run: echo "Check html report https://zmaiga.github.io/ATMproject/coverage.html"

    - name: Line Coverage Quality Gate
      working-directory: ${{github.workspace}}
      shell: bash
      # Query for project's coverage and compare with the gate requirements
      run: NUMBER=$(cpptestcov query -coverage LC .coverage) && if [ $NUMBER -lt $LINE_COV_GATE ]; then echo "Line coverage quality gate failed"; echo "Expected result $LINE_COV_GATE%, achieved $NUMBER%"; false; else echo "Line coverage quality gate passed with $NUMBER% (required $LINE_COV_GATE%)"; true; fi      
          echo "Check html report https://zmaiga.github.io/ATMproject/coverage.html"
    - name: MCDC Coverage Quality Gate
      working-directory: ${{github.workspace}}
      shell: bash
      # Query for project's coverage and compare with the gate requirements
      run: NUMBER=$(cpptestcov query -coverage MCDC .coverage) && if [ $NUMBER -lt $MCDC_COV_GATE ]; then echo "MCDC coverage quality gate failed"; echo "Expected result $MCDC_COV_GATE%, achieved $NUMBER%"; false; else echo "MC/DC coverage quality gate passed with $NUMBER% (required $MCDC_COV_GATE%)"; true; fi  
          echo "Check html report https://zmaiga.github.io/ATMproject/coverage.html"